############################################
### German Credit Application
############################################

#--- Setup ----
# To run MOC
# devtools::install("../counterfactuals/")
library("counterfactuals")

library("mlr")
library("mlrCPO")
library("ggplot2")
library("iml")

best.params = readRDS("../saved_objects/best_configs.rds")  # generated by irace in folder appendix_irace
USE_TRAINED_MODEL = TRUE
PARALLEL = TRUE

###---- Get data ----
credit = read.csv("german_credit_data.csv", row.names = 1, stringsAsFactors = TRUE)
names(credit)
# omit rows with NA entries
credit = na.omit(credit)
# join groups with small frequencies
levels(credit$Purpose) = c("others", "car", "others", "others",
  "furniture", "radio/TV", "others", "others")
levels(credit$Saving.accounts) = c("little", "moderate", "rich", "rich")
# Colnames to lower
names(credit) = tolower(names(credit))
# Drop levels
credit = droplevels.data.frame(credit)

###---- Define xinterest and training/test data ----
# Separate xinterest from training dataset
x.interest = credit[1,]
credit = credit[-1,]

###---- Train model ----
if (USE_TRAINED_MODEL) {
  credit.model = readRDS("model_svm.rds")
} else {
  credit.task = makeClassifTask(id = "credit",
    data = credit, target = "risk")
  lrn = makeLearner("classif.svm", predict.type = "prob")
  credit.lrn = cpoScale() %>>% cpoDummyEncode() %>>% lrn
  param.set = pSS(
    cost: numeric[0.01, 1]
  )
  
  TUNEITERS = 100L
  RESAMPLING = cv5
  
  if (PARALLEL) {
    parallelMap::parallelStartSocket(parallel::detectCores(), level = "mlr.tuneParams")
  }
  
  ctrl = makeTuneControlRandom(maxit = TUNEITERS * length(param.set$pars))
  lrn.tuning = makeTuneWrapper(lrn, RESAMPLING, list(mlr::acc), param.set, ctrl, show.info = FALSE)
  res = tuneParams(lrn, credit.task, RESAMPLING, par.set = param.set, control = ctrl,
    show.info = FALSE)
  performance = resample(lrn.tuning, credit.task, RESAMPLING, list(mlr::acc))$aggr
  
  if (PARALLEL) {
    parallelMap::parallelStop()
  }
  credit.lrn = setHyperPars2(credit.lrn, res$x) 
  credit.model = mlr::train(credit.lrn, credit.task)  # use mlr:: in case caret is loaded somewhere
}

pred = Predictor$new(model = credit.model, data = credit, class = "good")

# fit conditionals
ctr = partykit::ctree_control(maxdepth = 5L)
set.seed(1234)
cond = fit_conditionals(pred$data$get.x(), ctrl = ctr)

###---- Compute counterfactuals ----
pred$predict(x.interest)

set.seed(1000)
system.time({credit.cf = Counterfactuals$new(predictor = pred, 
  x.interest = x.interest, conditionals = cond,
  target = c(0.5, 1), epsilon = 0, generations = list(mosmafs::mosmafsTermStagnationHV(10),
    mosmafs::mosmafsTermGenerations(200)), 
  mu = best.params$mu, 
  p.mut = best.params$p.mut, p.rec = best.params$p.rec, 
  p.mut.gen = best.params$p.mut.gen, 
  p.mut.use.orig = best.params$p.mut.use.orig, 
  p.rec.gen = best.params$p.rec.gen, initialization = "icecurve",
  p.rec.use.orig = best.params$p.rec.use.orig)})

# Number of counterfactuals
nrow(credit.cf$results$counterfactuals)
id = credit.cf$results$counterfactuals$dist.target == 0
sum(id)

# Focus counterfactuals that met target
credit.cf$results$counterfactuals = credit.cf$results$counterfactuals[which(id), ]
credit.cf$results$counterfactuals.diff = credit.cf$results$counterfactuals.diff[which(id), ]

# Get relative frequency of feature changes
credit.cf$get_frequency()


###---- Plots ----
a = credit.cf$plot_parallel(features = c("duration", "credit.amount"), plot.x.interest = FALSE)
a = a + scale_x_discrete(expand = c(0.1, 0.1), labels= c("duration", "credit amount"))
a
b = credit.cf$plot_surface(features = c("duration", "credit.amount"))
b
c = credit.cf$plot_hv()
c
