#--- Setup ----
# To run MOC
# load `iml` and `counterfactuals` like "normal" packages.
# in the future this would just be library("counterfactuals").
devtools::load_all("../iml", export_all = FALSE)
devtools::load_all("../counterfactuals", export_all = FALSE)

library("mlr")
library("mlrCPO")
library("ggplot2")

best.params = best.params = readRDS("../saved_objects/best_configs.rds")  # generated by irace in folder appendix_irace

set.seed(123)
load("bike.RData")
x.interest = bike[1,]
bike = bike[-1,]
task = makeRegrTask(data = bike, target = "cnt")
mod = train("regr.randomForest", task)
pred = Predictor$new(mod, data = bike[-which(names(bike) == "cnt")], y = bike$cnt)
bike.x = bike[names(bike) != 'cnt']
pred$predict(newdata = x.interest) # 1767.934

####################################################

credit.cf = Counterfactuals$new(predictor = pred, 
  x.interest = x.interest, 
  target = c(3000, Inf), epsilon = 0, 
  generations = list(mosmafs::mosmafsTermStagnationHV(10),
    mosmafs::mosmafsTermGenerations(200)), 
  mu = best.params$mu, 
  p.mut = best.params$p.mut, p.rec = best.params$p.rec, 
  p.mut.gen = best.params$p.mut.gen, 
  p.mut.use.orig = best.params$p.mut.use.orig, 
  p.rec.gen = best.params$p.rec.gen, initialization = "icecurve",
  p.rec.use.orig = best.params$p.rec.use.orig)

nrow(credit.cf$results$counterfactuals)
id = credit.cf$results$counterfactuals$dist.target == 0
sum(id)

# Focus counterfactuals that met target
credit.cf$results$counterfactuals = credit.cf$results$counterfactuals[which(id), ]
credit.cf$results$counterfactuals.diff = credit.cf$results$counterfactuals.diff[which(id), ]

credit.cf$get_frequency(plot = TRUE, subset.zero = TRUE)
dif = credit.cf$results$counterfactuals.diff[,names(bike.x)]
namsdif = names(dif)[which(!apply(dif, MARGIN = 2L, FUN = function(x) all(x %in% c(0, "0"))))]
p1 = credit.cf$plot_parallel(features = namsdif)
p2 = credit.cf$plot_surface(features = c("temp", "hum"))

# ggsave(plot = p1, filename = "counterfactuals_bike_para.pdf", width = 6.2, height = 3.5)
# ggsave(plot= p2, 
#   filename = "counterfactuals_bike_sp.pdf", width = 6.2, height = 5)
